name: 'Telegram Bot Action'
description: 'Send messages to Telegram from GitHub Actions.'
author: 'BrainXio'
inputs:
  bot_token:
    description: 'Telegram Bot Token'
    required: true
  chat_id:
    description: 'Telegram Chat ID'
    required: true
  message:
    description: 'Message to send or path to a document containing the message'
    required: true
  parse_mode:
    description: 'Message format (Markdown or HTML)'
    required: false
    default: 'Markdown'
runs:
  using: 'composite'
  steps:
    - name: Send Info to Telegram
      shell: bash
      env:
        INPUT_BOT_TOKEN: ${{ inputs.bot_token }}
        INPUT_CHAT_ID: ${{ inputs.chat_id }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_PARSE_MODE: ${{ inputs.parse_mode }}
      run: |
        #!/bin/bash

        bot_token=$INPUT_BOT_TOKEN
        chat_id=$INPUT_CHAT_ID
        message=$INPUT_MESSAGE
        parse_mode=${INPUT_PARSE_MODE:-Markdown}

        url="https://api.telegram.org/bot${bot_token}/sendMessage"

        if [ -f "$message" ]; then
          # If the message is a file, read the content of the file
          message_content=$(<"$message")
        else
          # If the message is not a file, use it as is
          message_content="$message"
        fi

        payload=$(cat <<EOF
        {
            "chat_id": "${chat_id}",
            "parse_mode": "${parse_mode}",
            "text": "${message_content}"
        }
        EOF
        )

        response=$(curl -s -X POST -H "Content-Type: application/json" -d "${payload}" "${url}")
        if [ $? -eq 0 ]; then
            echo "Message sent successfully: ${response}"
        else
            echo "Action failed with error: ${response}"
        fi

