name: 'Telegram Bot Action'
description: 'Send messages to Telegram from GitHub Actions.'
author: 'BrainXio'
inputs:
  bot_token:
    description: 'Telegram Bot Token'
    required: true
  chat_id:
    description: 'Telegram Chat ID'
    required: true
  message:
    description: 'Message to send'
    required: true
  parse_mode:
    description: 'Message format (Markdown or HTML)'
    required: false
    default: 'Markdown'
runs:
  using: 'composite'
  steps:
    - name: Send Info to Telegram
      shell: bash
      run: |
        bot_token=$INPUT_BOT_TOKEN
        chat_id=$INPUT_CHAT_ID
        message=$INPUT_MESSAGE
        parse_mode=${INPUT_PARSE_MODE:-Markdown}

        url="https://api.telegram.org/bot${bot_token}/sendMessage"

        payload=$(cat <<EOF
        {
            "chat_id": "${chat_id}",
            "parse_mode": "${parse_mode}",
            "text": "${message}"
        }
        EOF)

        response=$(curl -s -X POST -H "Content-Type: application/json" -d "${payload}" "${url}")
        if [ $? -eq 0 ]; then
            echo "Message sent successfully: ${response}"
        else
            echo "Action failed with error: ${response}"
        fi
